name: Sync GitHub to S3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Set Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ASIAVJCW7LIIG7C5FOFW
        aws-secret-access-key: If65UpdtHQf+9xL/rFrIN8ncl42R/G5ujHpsP5yp
        aws-session-token: FwoGZXIvYXdzEPz//////////wEaDLjFpFTgZF+LwHjb1yK+AcQvG952InQL2KlaqogTfYTnzCwYqwSmf8b6U5ct5uaN1g8IhHqhMT5v+Sm7CrNGOavbZLGOD1O5EWBpT6YDfbH9MDWABLOQsTo/p+rCvT/FLOntuhVn3WpKpa46O2V4XGxs6HhASvycoerdCRB/eVxxBLkUBTV5S77DI2f272FGcv1W/FGZcfFj/ruoNKuzAYkLI3ogDGcX1zJ97lJ/i/2MDbxKBW2IOkoB4EJILV1CjejvWZqog8JWQYsRHpQo5PeJmAYyLc4YCuaCbBy+6IahJcTyoPD2H6d6EvppSBDk88cC9Ox8FqHGkp8LcQW+dNQwFA==
        aws-region: us-east-1

    - name: Deploy objects to S3 bucket
      run: |
        aws s3 sync ./ s3://bucket-aws-s3-felipe-duran \
        --exclude '.git/*' \
        --exclude '.github/*' \
        --exclude 'README.md' \
        --follow-symlinks \
        --delete